# MATLAB → NumPy Cheat Sheet

Bu notebook, MATLAB kullananlar için NumPy/Python karşılıklarını hızlıca öğrenmek amacıyla hazırlanmıştır.

Amaç:
- Temel syntax farkları
- Indexing
- Linear algebra
- Broadcasting mantığı

## Array oluşturma

In [1]:
# MATLAB
# A = [1 2; 3 4]

# NumPy
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

print(A)

[[1 2]
 [3 4]]


## Indexing (ÇOK ÖNEMLİ)

MATLAB: 1-based  
NumPy: 0-based

In [2]:
A = np.array([[1, 2],
              [3, 4]])

# MATLAB: A(1,1)
print(A[0, 0])  # NumPy

1


## Slicing

In [3]:
# MATLAB: A(:,1)
print(A[:, 0])  # tüm satırlar, 1. kolon

# MATLAB: A(1,:)
print(A[0, :])  # 1. satır

[1 3]
[1 2]


## Element-wise vs Matrix operations

In [4]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise (MATLAB: .*)
print(A * B)

# Matrix multiply (MATLAB: *)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


## Transpose

In [5]:
print(A.T)

[[1 3]
 [2 4]]


## Shape & Size

In [6]:
print(A.shape)   # (2,2)
print(A.size)    # 4

(2, 2)
4


## Loop yerine vectorization kullan

In [7]:
# KÖTÜ
result = []
for x in range(5):
    result.append(x**2)

# İYİ
arr = np.arange(5)
print(arr ** 2)

[ 0  1  4  9 16]


## Broadcasting

NumPy otomatik genişletir (MATLAB'da daha sınırlı)

In [8]:
A = np.array([[1, 2],
              [3, 4]])

b = np.array([10, 20])

print(A + b)

[[11 22]
 [13 24]]


## Random

In [9]:
# MATLAB: rand(2,2)
print(np.random.rand(2,2))

[[0.29650915 0.41096718]
 [0.31022193 0.5285637 ]]


## Linear Algebra

In [10]:
A = np.array([[1, 2],
              [3, 4]])

# determinant
print(np.linalg.det(A))

# inverse
print(np.linalg.inv(A))

# eigenvalues
print(np.linalg.eig(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


## Özet

- MATLAB → 1-based index
- NumPy → 0-based index
- MATLAB → matrix default
- NumPy → array default
- MATLAB → * = matrix multiply
- NumPy → * = element-wise, @ = matrix multiply
- NumPy → broadcasting güçlü